### PR TITLE
add file app.R and folder tests/testthat with file test_piat_random.R

### PR DESCRIPTION
**Pull request by ViolaLongGold**
This pull request:
- creates a new file app.R into inst
- creates folders tests and testthat
- creates a nwe file test_piat_random.R to folder tests/testthat

test_piat_random tests the PIAT for expected wording and simulates testing by giving random answers using app.R.

@pmcharrison I get an error when expecting "No match" as an answer to one of the training questions (button with button id = "No match"). I have marked this line with three question marks (line 63). Could you check that, please? Thank you!

### CODE REVIEW

**Comment by pmcharrison** [comment]
Hi Viola, thanks for this, and great job! I still find it quite magical seeing these automated tests running.

I found the problem - the original PIAT implementation had HTML buttons with whitespace in the IDs, which caused the app tester to fail. I fixed this and now it works (but the testing code needed to change slightly).

My fixes are now on the master branch of PIAT. In addition, the changes I made to your testing code can be found at https://github.com/pmcharrison/piat/tree/ViolaLongGold-master (I didn't have permissions to push to your original repository). Feel free to incorporate them into your proposed pull request to get the test working.

**Review by ViolaPsch — APPROVED** [review]
Thanks for fixing this!

**Comment by ViolaLongGold** [comment]
Hi Peter, I suppose the green check mark means that the test is working now, right? Can you merge the pull request now, so we can close the pull request? I hope this worked as it should ... ? 😕

**Comment by pmcharrison** [comment]
Hi Viola, it wasn't quite ready yet. The green check mark didn't correspond to the test, it just corresponded to a merge conflicts check. I did some more work on your branch to enable automatic testing and to get the automatic tests to run correctly. There is a pull request for it here: https://github.com/ViolaLongGold/piat/pull/1 

I think if you accept the pull request in your repository, then let me know, that should update the pull request in this repository, and everything should finally work? Not sure, sorry that it's complicated....

**Comment by pmcharrison** [comment]
Thanks @ViolaLongGold for the pull request! :-)

**Pull request merged**
